name:        Site Name
dev:         true
relative_paths: true

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     [ sass, Rakefile, codekit-config.json ]

future:      true
show_drafts: nil
limit_posts: 0
pygments:    false

relative_permalinks: false

permalink:   /:categories/:title/
paginate_path: 'page:num'
